openapi: 3.0.1 
info:
    title: AI Sportsbook
    description: Retrieve current odds for various sports and historical data for sports teams and players.
    version: "v1"
servers:
    - url: https://chatgpt-plugin-demo-espositogriffin.replit.app/
paths:
    /sports:
        get:
            operationId: getInSeasonSports
            summary: Retrieves a list of the current sports that are in-season and have available betting odds.
#            parameters:
#                - in: query
#                  name: symbol
#                  schema:
#                      type: string
#                  description: The symbol of the stock to get a quote for. For example, the stock symbol MSFT represents the company Microsoft.
            responses:
                "200":
                    description: OK